name: Forge Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        source $HOME/.foundry/bin/foundryup

    - name: Install Dependencies
      run: forge install

    - name: Run forge test
      run: forge test
      continue-on-error: true

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml
